# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'JRMedical' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JRMedical
  pod 'FrameAccessor', '~> 2.0'
  pod 'RegexKitLite', '~> 4.0'
  pod 'BlocksKit', '~> 2.2'
  pod 'FXKeychain', '~> 1.5'
  pod 'HYBNetworking', '~>2.0.1'
  pod 'SDCycleScrollView', '~> 1.65'
  pod 'NSString-Hashes', '~> 1.2.2'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'Masonry'
  pod "YYKit"
  pod 'SDAutoLayout', '~> 2.1.3'
  pod 'SCLAlertView-Objective-C'
  pod 'IQKeyboardManager'


end
